services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres17
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: